---

- name: package-upgrade | upgrade packages
  apt:
    name: "*"
    state: latest
  register: apt_update
  retries: 5
  until: apt_update is success

# - name: package-upgrade | upgrade system
#   apt:
#     upgrade: dist
#   register: apt_upgrade
#   retries: 5
#   until: apt_upgrade is success
