---

packages:
  deb:
    htop_version: 3.0.2-1
  install:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - dnsutils
  - ebtables
  - ethtool
  - git
  - gnupg-agent
  - gnupg2
  - haveged
  - hdparm
  - iperf3
  - iputils-ping
  - ipvsadm
  - jq
  - lvm2
  - neofetch
  - net-tools
  - netcat
  - nfs-common
  - nmap
  - ntpdate
  - open-iscsi
  - psmisc
  - python3
  - python3-openssl
  - python3-pip
  - rsync
  - scsitools
  - socat
  - software-properties-common
  - traceroute
  - unattended-upgrades
  - unzip
  - vim
  remove:
  - apparmor
  - apport
  - bcache-tools
  - btrfs-progs
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - tmux
  - ubuntu-advantage-tools
  - ufw
  