---
- name: longhorn | meta | apply labels
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/create-default-disk=config
  loop:
  - "{{ groups['worker'] }}"
  register: apply_longhorn_labels
  retries: 5
  until: apply_longhorn_labels is success
  when:
  - k3s_control_node is defined
  - k3s_control_node
  - hostvars[item].longhorn.enabled is defined
  - hostvars[item].longhorn.enabled == true

- name: longhorn | meta | apply annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl annotate --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/default-disks-config='[{"path":"{{ hostvars[item]['longhorn']['mointpoint'] }}", "name":"longhorn", "allowScheduling":true}]'
  loop:
  - "{{ groups['worker'] }}"
  register: apply_longhorn_annotations
  retries: 5
  until: apply_longhorn_annotations is success
  when: 
  - k3s_control_node is defined
  - k3s_control_node
  - hostvars[item].longhorn.enabled is defined
  - hostvars[item].longhorn.enabled == true

- name: longhorn | meta | remove labels
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/create-default-disk-
  loop:
  - "{{ groups['worker'] }}"
  register: remove_longhorn_labels
  retries: 5
  until: remove_longhorn_labels is success
  when: 
  - k3s_control_node is defined
  - k3s_control_node
  - (hostvars[item].longhorn.enabled is not defined or not hostvars[item].longhorn.enabled)

- name: longhorn | meta | remove annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl annotate --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/default-disks-config-
  loop:
  - "{{ groups['worker'] }}"
  register: remove_longhorn_annotations
  retries: 5
  until: remove_longhorn_annotations is success
  when:
  - k3s_control_node is defined
  - k3s_control_node
  - (hostvars[item].longhorn.enabled is not defined or not hostvars[item].longhorn.enabled)
