---

# ansible options
ansible_user: "ubuntu"
local_user: "{{ ansible_user }}"

# k3s options
k3s_version: v1.17.2+k3s1
#k3s_master_cli: "--docker --default-local-storage-path=/dev/shm --flannel-backend=none --no-deploy servicelb --no-deploy traefik"
k3s_master_cli: --default-local-storage-path=/dev/shm --no-deploy servicelb --no-deploy traefik --flannel-backend=host-gw
#k3s_worker_cli: "--docker"
k3s_worker_cli:
k3s_copy_config_local: false
k3s_master: "{{ hostvars[groups['master'][0]]['ansible_nodename'] }}"
k3s_master_lb: "{{ k3s_master }}"

# github options
github_username:
github_k8s_reponame: k8s-cluster

# ceph options
ceph:
  zap_disks: false
  disks:
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd

# server options
timezone: America/New_York
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
REPO_ROOT: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
kubernetes_pod_network:
  cni: flannel # calico / flannel
  bgp: disabled # Enabled / Disabled
  calico_manifest_file: "{{ REPO_ROOT }}/cluster/kube-system/calico/calico.yaml"
  calico_bgp_peer: 10.20.0.1
  calico_bgp_as: 64512
  cidr: '10.244.0.0/16'
allowed_kubernetes_access:
  - 10.9.18.225
  - 10.20.100.46
kubernetes_prometheus_alertmanager_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-alertmanager.yaml
kubernetes_prometheus_podmonitor_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-podmonitor.yaml
kubernetes_prometheus_prometheus_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheus.yaml
kubernetes_prometheus_prometheusrules_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheusrules.yaml
kubernetes_prometheus_servicemonitor_manifest_file: https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubernetes_flux_values: "{{ REPO_ROOT }}/cluster/flux/flux/flux-values.yaml"
kubernetes_helm_operator_values: "{{ REPO_ROOT }}/cluster/flux/helm-operator/helm-operator-values.yaml"
