---

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted
  listen: systemd-timesyncd configuration changed

- name: Write adjtime
  command: hwclock --systohc
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
  listen: systemd-timesyncd configuration changed
