---

- name: "package-install: common packages"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg-agent
    - gnupg2
    - haveged
    - hdparm
    - htop
    - jq
    - nfs-common
    - psmisc
    - python3
    - python3-pip
    - python3-openssl
    - rsync
    - socat
    - software-properties-common
    - unzip
    - vim
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
