- hosts:
  - worker
  become: true
  gather_facts: false
  vars_prompt:
    name: "nuke_confirmation"
    prompt: "This will DESTROY your longhorn volumes. Do you wish to continue? [Y/n]"
    default: "n"
    private: no
  any_errors_fatal: yes
  pre_tasks:
  - name: check confirmation
    fail: msg="Abort."
    when:
    - nuke_confirmation != "Y"

  - name: check longhorn is enabled
    fail: msg="Abort."
    when:
    - longhorn.enabled == false

  roles:
  - longhorn