helmOperator:
  create: false
git:
  url: "git@github.com:k8s-at-home/k8s-cluster"
  path: "cluster"
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
